version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - app-network

  kafka:
    image: wurstmeister/kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "mail_topic:1:1"
    depends_on:
      - zookeeper
    networks:
      - app-network

  mongo:
    image: mongo:4.4.18
    restart: always
    ports:
      - "27017"
    networks:
      - app-network

  api_service:
    build: .
    restart: always
    ports:
      - "8080:8080"
    env_file:
      .env
    depends_on:
      - mongo
      - kafka
    networks:
      - app-network

networks:
  app-network:
    driver: bridge